### ISSUE TITLE
Missing Option(Menu Breakpoint), Search issue in mobil menu in Version 3.0!!!!! 

### ISSUE THREAD

**Issue by JidWictut** [brainstormforce/astra#2435]
Hello,
I have now updated my site to the latest version (Theme and Pro).
In the process I noticed a few more problems:

**1. Where do I set the menu breakpoint? I have now changed this by a code snippet from your site. But that's definitely not how it's supposed to be. Before you could set it without code.
2. I can't add a search function to my mobile menu. No matter if widget or shortcode. As soon as I click on the search the menu closes.**

Regards

**Comment by vrundakansara** [comment]
Hello @JidWictut , thank you for reporting this to us.

> 1. Where do I set the menu breakpoint? I have now changed this by a code snippet from your site. But that's definitely not how it's supposed to be. Before you could set it without code.

I would like to inform you that, this feature is already under development. Only we are handling this issue in a different way now after v3.0.0. Now, users do not need to change the breakpoint to see the mobile layout on the desktop. He can simply add the Toggle Button and Off-Canvas menu on the desktop itself. Along with it comes a number of customization options too. You can further track this feature here - #2208 

> 2. I can't add a search function to my mobile menu. No matter if widget or shortcode. As soon as I click on the search the menu closes.

I tried doing so, and I recorded a [video here](https://share.getcloudapp.com/L1uNloeq).
Is there anything that I am missing? It would be helpful if you elaborate or share some references.


_Regards,
Vrunda Kansara_

**Comment by JidWictut** [comment]
Hello,

because of the search function in the menu:
If I simulate it, as they do, on the computer, it works. But on my smartphone(mobile device) it does not work. You have to test it with a smartphone(mobile device) and not with the desktop.
My page: [www.dinkelliebe.de](url)

With kind regards

**Comment by vrundakansara** [comment]
Hello @JidWictut , yes I see.
We have lined up a task for this and we will release this very soon. You can probably expect this fixed in v3.3.0.

**Comment by JidWictut** [comment]
Hello,
thank you for your reply and support.
I am waiting for the update.

**Comment by JidWictut** [comment]
Hello,

I have installed the latest update (3.3.0) on my test site. Unfortunately, the problem with the search in the menu is not fixed. Pity that it does not work.

**Comment by JidWictut** [comment]
Hello,

I have installed the latest update (3.4.1) on my site. Unfortunately, the problem with the search in the menu is not fixed :(

**Comment by vrundakansara** [comment]
@JidWictut - As I mentioned above the issue was fixed in v3.3.0.
I tried the same link you provided on my phone and I see this. Is there something that I am missing? Would you please elaborate more about the issue with a screencast or GIF?


https://user-images.githubusercontent.com/11641718/117619732-3f927500-b18d-11eb-8571-2bed773e0d2c.MP4

**Comment by JidWictut** [comment]
Hello,

unfortunately the search does not work for me. My smartphone is a S20+ and I use the Chrome browser but also with Firefox it does not work.


https://user-images.githubusercontent.com/65712457/117622644-254b9d80-b173-11eb-843f-a07dc703815f.mp4

**Comment by JidWictut** [comment]
The bug has been fixed with today's update (3.4.3).
Thank you very much.
